prisma/prisma-examples

go-cli-app/Gopkg.lock, go-cli-app/main.go, go-cli-app/prisma-client/prisma.go
Generated via Go client from latest beta `prisma/1.19.0-beta.0` - `npm install -g prisma@beta`
=> fix(go): generate after error fix

go-cli-app/main.go
Replaced `if-else` to `switch` statement, because of this more effective.
[See](https://golang.org/doc/effective_go.html#switch)
=> Replaced if-else to switch statement

.github/readmes/_using-the-graphql-api-auth.md, .github/readmes/_using-the-graphql-api-subs.md, flow/graphql/README.md, node/graphql-auth/README.md, node/graphql-subscriptions/README.md, typescript/graphql-auth/README.md, typescript/graphql-subscriptions/README.md
@nikolasburk Hello,That's the changes you suggest me before. Updated the template and re-generate the READMEs. Hope for you to check.
=> change readme

.github/readmes/javascript/_setup-2.md, .github/readmes/typescript/_setup-2.md, javascript/cli-app/README.md, javascript/graphql-auth/README.md, javascript/graphql-subscriptions/README.md, javascript/graphql/README.md, javascript/grpc/README.md, javascript/rest-express/README.md, javascript/script/README.md, typescript/cli-app/README.md, typescript/graphql-apollo-server/README.md, typescript/graphql-auth/README.md, typescript/graphql-crud/README.md, typescript/graphql-subscriptions/README.md, typescript/graphql/README.md, typescript/grpc/README.md, typescript/rest-express/README.md, typescript/script/README.md
Updates all JavaScript and TypeScript example READMEs with alternative instructions on how to "Connect to your own database"
=> Improve READMEs

deployment-platforms/google-cloud-functions/index.js, deployment-platforms/netlify/functions/index.js, deployment-platforms/up/app.js, deployment-platforms/zeit-now/api/index.js, javascript/graphql-auth/prisma/seed.js, javascript/graphql-auth/src/index.js, javascript/graphql/prisma/seed.js, javascript/grpc/prisma/seed.js, javascript/rest-express/src/index.js
Since we now perform named export, .default will not work and throw an error.
This PR fixes that issue
=> change Photon.default() to Photon()

deployment-platforms/codesandbox/package.json, deployment-platforms/docker/package.json, deployment-platforms/netlify/package.json, deployment-platforms/serverless/package.json, deployment-platforms/up/package.json, deployment-platforms/zeit-now/api/package.json, javascript/graphql-auth/package.json, javascript/graphql/package.json, javascript/grpc/package.json, javascript/rest-express/package.json, javascript/script/package.json, typescript/graphql-apollo-server/package.json, typescript/graphql-auth/package.json, typescript/graphql/package.json, typescript/grpc/package.json, typescript/rest-express/package.json, typescript/script/package.json
Reverts prisma/prisma-examples#827
=> Revert "Update dependency prisma2 to v2.0.0-preview-9.1 (prisma2)"

javascript/graphql-auth/package.json, javascript/graphql-auth/src/resolvers/AuthPayload.js, javascript/graphql-auth/src/resolvers/Mutation.js, javascript/graphql-auth/src/schema.graphql, typescript/graphql-auth/package.json, typescript/graphql-auth/src/resolvers/Mutation.ts, typescript/graphql-auth/src/schema.graphql
Potentially fixes https://github.com/prisma/prisma2/issues/550
=> Use bcryptjs in place of bcrypt

misc/react-graphql-fullstack/server/package.json, misc/react-graphql-fullstack/server/src/schema.ts, typescript/graphql-apollo-server/package.json, typescript/graphql-apollo-server/src/schema.ts, typescript/graphql-auth/package.json, typescript/graphql-auth/src/schema.ts, typescript/graphql/package.json, typescript/graphql/src/schema.ts
=> fix: ts nexus use require.resolve sans ext

typescript/graphql-apollo-server/tsconfig.json
It's closed: https://github.com/prisma/nexus-prisma/issues/82
=> Remove unbroken config line

typescript/graphql/README.md
Added note to change directory and changed the database name to `dev`  to match the name of the sqlite database in the repo.
=> Clarified "Change Your Database Schema" Instructions in README

typescript/rest-express/src/index.ts
Might also have to be applied to other files. Feel free to edit the PR to do that.
=> fix(rest-express): sample requests link was broken

javascript/graphql-auth/src/permissions/index.js, typescript/graphql-auth/src/permissions/index.ts
=> fix isPostOwner

javascript/rest-nextjs/components/Header.jsx, javascript/rest-nextjs/components/Post.jsx, javascript/rest-nextjs/package.json, javascript/rest-nextjs/pages/create.jsx, javascript/rest-nextjs/pages/drafts.jsx, javascript/rest-nextjs/pages/index.jsx, javascript/rest-nextjs/pages/p/[id].jsx, javascript/rest-nextjs/pages/signup.jsx
- Updated nextjs to version 9.3
- Changed getInitialProps() to getServerSideProps()
- Changed all Class Components to Functional Components using hooks
- Post Component moved out from drafts.jsx and index.jsx
- Implemented post content render using the React Markdown library
=> Updated nextjs, react and other dependencies

typescript/rest-nextjs/components/Header.tsx, typescript/rest-nextjs/components/Layout.tsx, typescript/rest-nextjs/components/Post.tsx, typescript/rest-nextjs/package.json, typescript/rest-nextjs/pages/create.tsx, typescript/rest-nextjs/pages/drafts.tsx, typescript/rest-nextjs/pages/index.tsx, typescript/rest-nextjs/pages/p/[id].tsx, typescript/rest-nextjs/pages/signup.tsx
- Updated nextjs to version 9.3
- Changed getInitialProps() to getServerSideProps()
- Changed all Class Components to Functional Components using hooks
- Post Component moved out from drafts.jsx and index.jsx
- Implemented post content render using the React Markdown library
- Better Types for components and functions
=> Updated nextjs, react and better TS support

javascript/rest-nextjs/components/Post.jsx, javascript/rest-nextjs/package.json, typescript/rest-nextjs/package.json
- Removed unused dependencies: express and tachyons from both JS and TS examples
- Post.jsx component fixed in JS rest-nextjs example to fix nested a tags error.
=> Remove unused dependencies and fixed Post component error

.github/scripts/slack-workflow-status.sh, .github/workflows/check-for-update.yaml
=> ci(check-for-update): enable update check slack reports

README.md
Short description how (and why) the repository branches are set up and how they are updated.
=> docs(README): About this repository

README.md
closes https://github.com/prisma/prisma-examples/issues/1829
=> docs(readme): update about section

deployment-platforms/vercel-graphql/.gitignore, deployment-platforms/vercel-graphql/api/_lib/context.ts, deployment-platforms/vercel-graphql/api/_lib/schema.ts, deployment-platforms/vercel-graphql/package.json, deployment-platforms/vercel-graphql/public/index.html, deployment-platforms/vercel-graphql/schema.graphql
- Upgrade `nexus-prisma` -> nexus-plugin-prisma/schema
- Make fields required in queries
- Add users queries
- Add better dev command
=> Improve Vercel GraphQL example

deployment-platforms/vercel-graphql/package.json
(as they come with nexus-plugin-prisma as well)
=> fix(vercel-graphql): add back postinstall hook, remove local prisma dependencies

deployment-platforms/aws-lambda/README.md, deployment-platforms/heroku/.gitignore, deployment-platforms/heroku/Procfile, deployment-platforms/heroku/README.md, deployment-platforms/heroku/package.json, deployment-platforms/heroku/prisma/schema.prisma, deployment-platforms/heroku/public/index.html, deployment-platforms/heroku/src/index.js, deployment-platforms/vercel-graphql/README.md, deployment-platforms/vercel/README.md
Related issue: https://github.com/prisma/docs/issues/616
=> feat(deployment/heroku): Add simple heroku example for deployment guide

.github/readmes/deployment-platforms/zeit-now/README.md, deployment-platforms/zeit-now/README.md
=> Remove Zeit Now

.github/workflows/keep-dev-branch-in-sync-with-master.yaml, .github/workflows/keep-prisma-dependencies-updated.yaml, .github/workflows/test.yaml
fix https://github.com/prisma/prisma/issues/3539
fix https://github.com/prisma/prisma-examples/issues/1988
=> ci(workflows): run workflows only under prisma org
